import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Atomic_Age } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";
import Link from "next/link";
import MainNav from "@/components/main_nav";
import { useApp } from "@/context/AuthContext";
import AppProviderWrapper from "@/components/app-context/AppProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const atomic_age = Atomic_Age({
  weight: "400",
  variable: "--font-atomicage",
  subsets:["latin"]
})

const materialSymbols = localFont({
 src:"./fonts/material-symbols-rounded.woff2",
 weight: "100 900",
 variable: "--font-material-symbols"
})



export const metadata: Metadata = {
  title: "Creating My New Epic Application",
  description: "Generated by create next app",
};


let loggedIn = false;



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${atomic_age.variable} ${materialSymbols.variable} h-full antialiased`} /*Loads fonts into the html for use later*/
    >
      <body className="min-h-full">
        <AppProviderWrapper>
        <MainNav />
        {children}
        </AppProviderWrapper>
      </body>
    </html>
  );
}
